services:
  - type: web
    name: assignment4-app
    env: node
    region: oregon
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && NODE_ENV=production npm start
    envVars:
      - key: NODE_ENV
        value: production
