services:
  - type: web
    name: assignment4-app
    env: node
    region: virginia
    buildCommand: cd frontend && npm ci --include=dev && npm run build && cd ../backend && npm install
    startCommand: cd backend && NODE_ENV=production npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: BASE_URL
        value: https://it202-hien-vo-section-103.onrender.com
